version: "3.9"

services:
  api:
    build:
      context: app/api           
      dockerfile: Dockerfile   
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models 

  ui:
    build:
      context: app/ui            
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models 
