services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Porta do Flask API
      - "8501:8501"  # Porta do Streamlit
    volumes:
      - ./app:/app
